name: lib.frontend.core.shared
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: marc <email@example.com>


dependencies:
  lib.core.rx:
    path: ../../../core/rx
  lib.core.di:
    path: ../../../core/di

dev_dependencies:
  test: ^0.12.0
