name: lib.core.units
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: marc <email@example.com>

dependencies:
  latlong: ^0.4.5
  units: ^0.0.7
  lib.core.shared:
    path: ../shared

dev_dependencies:
  test: ^0.12.0
