name: lib.frontend.core.auth
description: Authentication interfaces for the frontend, both mobile and web.
version: 0.0.1
#homepage: https://www.example.com
#author: marc <email@example.com>


dependencies:
  lib.core.di:
    path: ../../../core/di
  lib.core.validation:
    path: ../../../core/validation
  lib.frontend.core.shared:
    path: ../shared

dev_dependencies:
  test: ^0.12.0
